### ISSUE TITLE
Add iOS privacy manifests

### ISSUE THREAD

**Issue by a-yarimizu-dc** [wasabeef/flutter_ua_client_hints#105]
Hello,

In my project, we are working on supporting PrivacyManifest to meet the latest privacy requirements on iOS. 
Could you please confirm if there are plans to implement this support in the project?

I would appreciate any details regarding the plans and progress for implementing PrivacyManifest. Thank you for your consideration.

**Comment by wasabeef** [comment]
Released v1.4.0
