### ISSUE TITLE
Incorrect userAgent after brand name fix

### ISSUE THREAD

**Issue by gabimem** [wasabeef/flutter_ua_client_hints#107]
Since the brand name was corrected, the user agent string returns an incorrect value, instead of returning the application name, it returns the brand name. For example:

This value is expected:
`User-Agent: SampleApp/1.0.0 (iOS 14.2; iPhone; iPhone13,4; arm64v8)`

This value is returned:
`User-Agent: Apple/1.0.0 (iOS 14.2; iPhone; iPhone13,4; arm64v8)`

This is the function in question, in the file *ua_client_hints.dart*

```dart
/// e.g.. User-Agent: SampleApp/1.0.0 (Android 11; Pixel 4 XL; coral; arm64-v8a)
/// e.g.. User-Agent: SampleApp/1.0.0 (iOS 14.2; iPhone; iPhone13,4; arm64v8)
String _userAgent(Map<dynamic, dynamic> map) {
  return '${map['brand']}/${map['version']} (${map['platform']} ${map['platformVersion']}; ${map['model']}; ${map['device']}; ${map['architecture']})';
}
```

**Comment by wasabeef** [comment]
fixed v1.3.0 https://github.com/wasabeef/flutter_ua_client_hints/pull/110
